# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Weasley' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weasley
	pod 'SnapKit', '~> 5.0.0'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'GoogleSignIn'
  
  target 'WeasleyTests' do
    inherit! :search_paths
    pod 'Firebase'
  end
end
